# Generated by Django 4.1.4 on 2022-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
