# Generated by Django 4.1.4 on 2022-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
